cache:
  paths:
  - .irepo/
  - third_party/

stages:
- build
- deploy

generate_html:
  stage: build
  script:
    - echo setting up python virtual env
    - ci/pyenv.cmd up
    - echo we got here
    - set PATH=%PATH%;%_CI_TOOLS_DIR%\doxygen_1.8.15.windows.x64
    - cd scripts
    - python run.py --!core --!extended --!tools --!md
  artifacts:
    name: "%CI_JOB_NAME%"
    paths:
      - html/
    expire_in: 1 week
  only:
    refs:
      - master
      - staging_ci
  tags:
    - win

pages:
  stage: deploy
  script:
    - ci/pyenv.cmd up
    - cd scripts
    - python ci.py --publish-html
  artifacts:
    paths:
    - public
  only:
    refs:
      - master
      - staging_ci
  tags:
    - win
  when: always
