cache:
  paths:
  - .irepo/
  - .deps/
  - docs/

stages:
- build
- deploy

build:all:
  stage: build
  script:
    - call ci/pyenv.cmd update_pip
    - call ci/pyenv.cmd up
    - set PATH=%_CI_TOOLS_DIR%\doxygen;%VDIR%\Scripts;%PATH%
    - cd scripts
    - python run.py --html --build
  artifacts:
    name: "%CI_JOB_NAME%"
    paths:
      - include/
      - source/wrapper/include/
    expire_in: 1 week
  only:
    refs:
      - master
      - stage_ci
  tags:
    - win
    - git
    - docs

pages:
  stage: deploy
  script:
    - call ci/pyenv.cmd up
    - cd scripts
    - python ci.py --publish-html
  dependencies:
    - build:all
  artifacts:
    paths:
    - public
  only:
    refs:
      - master
      - stage_ci
  tags:
    - win
    - git
    - docs
  when: always

#linux:
#  image: loki18.04:latest
#  stage: build
#  only:
#  - branches
#  - tags
#  - merge_requests
#  tags:
#    - Linux
#  script:
#    - pwd
#    - ls -l
#    - ~/irepo/irepo select -d . third_party/linux.yml
#    - ~/irepo/irepo sync
#    - mkdir build
#    - cd build
#    - cmake -DCMAKE_BUILD_TYPE=Release ..
#    - make
