stages:
- build
- deploy

generate_html:
  stage: build
  script: ci/gen_docs.cmd
  only:
    - master@one-api/level_zero
  artifacts:
    name: "%CI_JOB_NAME%"
    paths:
      - html/
    expire_in: 1 week
  only:
    refs:
      - master
      - staging_ci
  tags:
    - win
    - python
    - doxygen
    - bt

pages:
  stage: deploy
  script: ci/publish_docs.cmd
  only:
    - master@one-api/level_zero
  artifacts:
    paths:
    - public
  only:
    refs:
      - master
      - staging_ci
  tags:
    - win
    - python
    - bt
  when: always

