stages:
- build
- deploy

generate_html:
  stage: build
  script: ci/gen_docs.cmd
  artifacts:
    name: "%CI_JOB_NAME%"
    paths:
      - html/

pages:
  stage: deploy
  script: ci/publish_docs.cmd
  artifacts:
    paths:
    - public