cache:
  paths:
  - .irepo/
  - third_party/

stages:
- build
- deploy

generate_html:
  stage: build
  script:
    - call ci/pyenv.cmd update_pip
    - call ci/pyenv.cmd up
    - set PATH=%PATH%;%_CI_TOOLS_DIR%\doxygen_1.8.15.windows.x64;%VDIR%\Scripts
    - cd scripts
    - python run.py --!core --!experimental --!tools --!rst
  artifacts:
    name: "%CI_JOB_NAME%"
    paths:
      - docs/html/
      - docs/ref/
    expire_in: 1 week
  only:
    refs:
      - master
      - staging_ci
  tags:
    - win
    - git
    - docs

pages:
  stage: deploy
  script:
    - call ci/pyenv.cmd up
    - cd scripts
    - python ci.py --publish-html
  artifacts:
    paths:
    - public
  only:
    refs:
      - master
      - staging_ci
  tags:
    - win
    - git
    - docs
  when: always

linux:
  image: loki18.04:latest
  stage: build
  only:
  - branches
  - tags
  - merge_requests
  tags:
    - Linux
  script:
    - pwd
    - ls -l
    - ~/irepo/irepo select -d . third_party/linux.yml
    - ~/irepo/irepo sync
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
