stages:
- build
- deploy

generate_html:
  stage: build
  script: ci/gen_docs.cmd
  only:
    - master@one-api/level_zero
  artifacts:
    name: "%CI_JOB_NAME%"
    paths:
      - html/
  tags:
    - windows

pages:
  stage: deploy
  script: ci/publish_docs.cmd
  only:
    - master@one-api/level_zero
  artifacts:
    paths:
    - public
  tags:
    - windows

linux:
  image: loki:latest
  stage: build
  only:
  - branches
  - tags
  - merge_requests
  tags:
    - Linux
  script:
    - pwd
    - ls -l
    - ~/irepo/irepo select -d . third_party/linux_embargo.yml
    - ~/irepo/irepo sync
    - mkdir build
    - cd build
    - cmake -GNinja .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release --clean-first --target all

windows:
  stage: build
  only:
  - branches
  - tags
  - merge_requests
  tags:
    - Build_VS2017
  variables:
    IREPO_CACHE_DIR: /.irepo
  script:
    - cd
    - dir
    - whoami
    - call /irepo/irepo select third_party\windows_embargo.yml
    - call /irepo/irepo sync
    - md build
    - cd build
    - cmake -G "Visual Studio 15 2017 Win64" .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release --clean-first --target ALL_BUILD
