stages:
- build
- deploy

generate_html:
  stage: build
  script: ci/gen_docs.cmd
  artifacts:
    name: "%CI_JOB_NAME%"
    paths:
      - html/
  tags:
    - windows

pages:
  stage: deploy
  script: ci/publish_docs.cmd
  artifacts:
    paths:
    - public
  tags:
    - windows

linux:
  image: loki:latest
  stage: build
  allow_failure: true
  only:
  - branches
  - tags
  - merge_requests
  tags:
    - Linux
  script:
    - pwd
    - ls -l
    - ~/irepo/irepo select -d . third_party/linux_embargo.yml
    - ~/irepo/irepo sync
    - mkdir build
    - cd build
    - cmake -GNinja .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release --clean-first --target all
