on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

env:
  http_proxy: http://proxy-dmz.intel.com:912
  https_proxy: http://proxy-dmz.intel.com:912
  VER: '1.12'

jobs:
  build:
    runs-on: [self-hosted, Linux]
    if: github.repository_owner == 'intel-innersource'
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install Mako==1.1.0 PyYAML==5.2
    - uses: actions/checkout@v4
      with:
        clean: true
        fetch-depth: 0
        fetch-tags: true
        path: spec
    - name: Generate spec artifacts
      working-directory: spec/scripts
      run: python3 ./run.py --debug '--!build' --ver $VER