on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

env:
  http_proxy: http://proxy-dmz.intel.com:912
  https_proxy: http://proxy-dmz.intel.com:912
  DOCKER_BUILDKIT: '1'
  VER: '1.12'

jobs:
  build:
    runs-on: [self-hosted, Linux]
    if: github.repository_owner == 'intel-innersource'
    steps:
    - uses: actions/checkout@v4
      with:
        clean: true
        fetch-depth: 0
        fetch-tags: true
        path: spec
    - name: Build container image
      run: | #bash
        docker build \
          --build-arg http_proxy=http://proxy-dmz.intel.com:912 \
          --build-arg https_proxy=http://proxy-dmz.intel.com:912 \
          -t ghcr.io/oneapi-src/spec-build:latest \
          - < spec/.github/docker/build.Dockerfile
    - name: Generate spec artifacts
      run: | #bash
        docker run \
          --rm \
          -v $PWD:$PWD \
          -w $PWD/spec/scripts \
          ghcr.io/oneapi-src/spec-build:latest \
          python3 ./run.py --debug '--!build' --ver $VER
